import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import App from "./App";
import AppTest from "./App.test";
import "./styles.css";
import './index.css';

import { Amplify } from 'aws-amplify';
import '@aws-amplify/ui-react/styles.css';
import awsExports from './aws-exports'; // This file is generated by `amplify init`
Amplify.configure(awsExports);

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(
  <React.StrictMode>
    {/* The BrowserRouter should wrap the App component at the top level. */}
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>
);
